version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:lts 
    steps:
      - checkout 
      - run: npm install 
      - run: npm test > test-results.txt 
      - store_artifacts:
          path: test-results.txt


workflows:
  build_and_test:
    jobs:
      - build_and_test

